version: '3.7'
services:
  top.api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: top-api
    restart: always
    ports:
      - 3030:3030
    environment:
      - MONGO_DB_HOST=mongo
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: mongo