name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: ghcr.io
          name: ghcr.io/AlexandrMers/api-top-generator/api-top-generator
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tags: "develop"